system_packages:
  - build-essential
  - net-tools
  - git
  - libpq-dev
  - python3
  - python3-dev
  - python3-pip
  - python3-venv
  - postgresql-client
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - iotop
  - sysstat
  - nginx
  - vim
  - supervisor

arch: amd64Ansible Automation Platform
ubuntu_release: focal

python_packages:
  - docker-compose

users:
  - name: anand
    authorized_keys:
      - authorized_keys/anand-bhuvanam-id-rsa.pub
      - authorized_keys/anand-x230-id-rsa.pub
    groups:
      - sudo
      - docker
  - name: kaustubh
    authorized_keys:
      - authorized_keys/nikochiko.keys
    groups:
      - sudo
      - docker
  - name: fossunited
    authorized_keys:
      - authorized_keys/anand-bhuvanam-id-rsa.pub
      - authorized_keys/anand-x230-id-rsa.pub
      - authorized_keys/nikochiko.keys
    groups:
      - sudo
      - docker
